site_name: 22eee.cn-紧急升级页面大通知
site_author: 22eee.cn
site_description: 经典影片(www.22eee.com.cn)推荐及独家原创内容，满足不同用户的观影需求。同时提供会员服务，享受无广告、蓝光画质等特权，打造沉浸式观影体验。
theme:
  name: readthedocs
nav:
  - Home: index.md
  - About: about.md
  - Features: features.md
  - Contact: contact.md
